# Generated by Django 3.2.7 on 2021-09-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nouns_triggers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredWebhooks',
            new_name='RegisteredWebhook',
        ),
    ]
