# Generated by Django 3.2.7 on 2021-09-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouns_triggers', '0002_rename_registeredwebhooks_registeredwebhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSeenAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
